apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  annotations:
    build.appstudio.redhat.com/commit_sha: '{{revision}}'
    build.appstudio.redhat.com/target_branch: '{{target_branch}}'
    pipelinesascode.tekton.dev/max-keep-runs: "3"
    pipelinesascode.tekton.dev/on-event: '[push]'
    pipelinesascode.tekton.dev/on-target-branch: '[main,master]'
  creationTimestamp: null
  labels:
    appstudio.openshift.io/application: build-suite-test-application-gebp
    appstudio.openshift.io/component: test-component-pac-klkr
    build.appstudio.openshift.io/component: test-component-pac-klkr
    pipelines.appstudio.openshift.io/type: build
  name: test-component-pac-klkr-on-push
  namespace: build-e2e-mgxi
spec:
  params:
  - name: git-url
    value: '{{repo_url}}'
  - name: revision
    value: '{{revision}}'
  - name: output-image
    value: quay.io/redhat-appstudio-qe/test-images:{{revision}}
  - name: dockerfile
    value: docker/Dockerfile
  - name: path-context
    value: .
  pipelineRef:
    bundle: quay.io/redhat-appstudio/build-templates-bundle:13f5d9c921b3f727684a00084037f673a0dc4273
    name: docker-build
  workspaces:
  - name: workspace
    persistentVolumeClaim:
      claimName: appstudio
    subPath: test-component-pac-klkr-on-push-{{revision}}
  - name: registry-auth
    secret:
      secretName: redhat-appstudio-registry-pull-secret
status: {}
