apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  annotations:
    build.appstudio.redhat.com/commit_sha: '{{revision}}'
    build.appstudio.redhat.com/pull_request_number: '{{pull_request_number}}'
    build.appstudio.redhat.com/target_branch: '{{target_branch}}'
    pipelinesascode.tekton.dev/max-keep-runs: "3"
    pipelinesascode.tekton.dev/on-event: '[pull_request]'
    pipelinesascode.tekton.dev/on-target-branch: '[main]'
  creationTimestamp: null
  labels:
    appstudio.openshift.io/application: build-suite-test-application-jrca
    appstudio.openshift.io/component: test-component-pac-ejai
    build.appstudio.openshift.io/component: test-component-pac-ejai
    pipelines.appstudio.openshift.io/type: build
  name: test-component-pac-ejai-on-pull-request
  namespace: e2e-test-zmxm
spec:
  params:
  - name: git-url
    value: '{{repo_url}}'
  - name: revision
    value: '{{revision}}'
  - name: output-image
    value: quay.io/redhat-appstudio-qe/test-images:on-pr-{{revision}}
  - name: path-context
    value: .
  - name: dockerfile
    value: Dockerfile
  pipelineRef:
    bundle: quay.io/redhat-appstudio/build-templates-bundle:510fa6e99f1fa1f816c96354bbaf1ad155c6d9c3
    name: docker-build
  workspaces:
  - name: workspace
    persistentVolumeClaim:
      claimName: appstudio
    subPath: test-component-pac-ejai-on-pull-request-{{revision}}
  - name: registry-auth
    secret:
      secretName: redhat-appstudio-registry-pull-secret
status: {}
